### ISSUE TITLE
Manifest and API keys errors

### ISSUE THREAD

**Issue by dendyaziz** [rtchagas/pingplacepicker#10]
> Task :app:processDebugManifest FAILED
X:\Android\beebagi\app\src\main\AndroidManifest.xml:22:18-91 Error:
	Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
	is also present at [androidx.core:core:1.1.0-alpha05] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:6:5-44:19 to override.

See http://g.co/androidstudio/manifest-merger for more information about the manifest merger.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
  	is also present at [androidx.core:core:1.1.0-alpha05] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
  	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:6:5-44:19 to override.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
6 actionable tasks: 1 executed, 5 up-to-date
ERROR: Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
	is also present at [androidx.core:core:1.1.0-alpha05] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:6:5-44:19 to override.

**Comment by rtchagas** [comment]
Hi @dendyaziz 

Your project is not using **AndroidX** and, therefore, some dependencies are clashing.

Please migrate your project to AndroidX in order to use PING and many new Android libraries and components.

This change to AndroidX will become inevitable sooner or later.

**Comment by dendyaziz** [comment]
Ok, I already migrated my project to androidx.
My next question, where I can get android api key?
I've got geolocation api key but can't found android api key on google console.

builder.setAndroidApiKey("YOUR_ANDROID_API_KEY")
                .setGeolocationApiKey("AIzaSy~~~~~~~~~~~~~~~~~M880A");

It shows "Couldn't load nearby places", but sometimes nearby places are loaded
![350822](https://user-images.githubusercontent.com/35209381/57228045-13433b80-703d-11e9-9848-7304e9b549ce.jpg)

**Comment by rtchagas** [comment]
You can create and Android Key the same way you created a Geolocation Key.

But in the key properties, just set it as an Android Restricted Key.
https://developers.google.com/places/android-sdk/signup#restrict-key

**Comment by dendyaziz** [comment]
Ok, it's working but it shows "couldn't find the selected place" when I select my current location using red pointer. all icons color and confirmation button turn into white too

![350822](https://user-images.githubusercontent.com/35209381/57230198-fc531800-7041-11e9-8f13-52278e7a9561.jpg)
![350826](https://user-images.githubusercontent.com/35209381/57230201-fc531800-7041-11e9-8740-63c9cf212bab.jpg)

**Comment by rtchagas** [comment]
Hi @dendyaziz 

That means that your Geolocation Key is wrong.

Please make sure that your Geolocation is configured **exactly** like this:
![image](https://user-images.githubusercontent.com/1816489/57405384-9780f480-71de-11e9-9f5d-96c0fc98bac3.png)

Regarding the icon colours, PING uses the @color/colorPrimary to these icons.
https://github.com/rtchagas/pingplacepicker/blob/1bb5b78060a4275f8f6f9f3d35721f374e7940dc/library/src/main/res/layout/item_place.xml#L40

Probably you have a conflicting style with PING.

Please also double check whether you enabled the support vectors in your app's build.gradle.
vectorDrawables.useSupportLibrary = true

**Comment by LinkIMSA** [comment]
The library not working
and some times "**works just one in the whole day"** ,i have tried to add tow key's with restriction on the geolocation and single key without restriction supports all api's Places and Geolocation
with no luck any idea to solve this issue

**Comment by vanyasem** [comment]
I have a 100% correct API key configured EXACTLY like this, and it even gets requests - as the counter in the API panel increases, but the library keeps throwing an error

**Comment by rtchagas** [comment]
@vanyasem 

What error is it throwing?
I have the demo and a different application using the library and everything is fine.

If you are getting errors while opening the picker **before showing the list of places**, you have a problem with your **Android key**.

If your get an error message while clicking on the "choose this place" button you have a problem with you **GeoLocation key**.

Just to be clear, the Android and Geolocation keys MUST be different.
The Android key must be secured with your apps's SHA1s as well.

**Comment by vanyasem** [comment]
@rtchagas my keys are different, and I have configured the Geolocation key exactly the same way as shown on your screenshot. I can see requests being made in the console, but the picker throws a "Couldn't find selected place..." error

**Comment by rtchagas** [comment]
@vanyasem 
So, the error happens when you click on the "Select this location" button?

**Comment by vanyasem** [comment]
@rtchagas Yep

**Comment by rtchagas** [comment]
Could you please send some logs when the "Couldn't find selected place..." is shown?

**Comment by vanyasem** [comment]
@rtchagas I'm not sure where to get them, logcat doesn't log anything suspicious

**Comment by vanyasem** [comment]
hm @rtchagas 
```
05-13 17:32:06.106 2061-2061/? W/Binder_B: type=1400 audit(0.0:635): avc: denied { ioctl } for path="socket:[251302]" dev="sockfs" ino=251302 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
05-13 17:32:06.106 2061-2061/? W/Binder_B: type=1400 audit(0.0:636): avc: denied { ioctl } for path="socket:[251302]" dev="sockfs" ino=251302 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
```

**Comment by vanyasem** [comment]
logcat throws a selinux exception every time i press se;ect this location

**Comment by rtchagas** [comment]
Probably not that...

Let's go for trials and errors...

- Is your Geolocation API (not the key) enabled in your Google APIs console?
- Remove any restriction in your Geolocation key and try again.

**Comment by vanyasem** [comment]
@rtchagas yep, it's enabled and it even gets requests as I'm mentioning for the third time. I tried removing restrictions, that made no difference

**Comment by rtchagas** [comment]
Please try to open this URL:
`https://maps.googleapis.com/maps/api/geocode/json?latlng=40.714224,-73.961452&key=[YOUR GEO KEY]`

I just need to be sure that the issue is library related and not a configuration or Google Maps issue.

**Comment by vanyasem** [comment]
The URL returns a JSON with New-York (written in Russian)

**Comment by vanyasem** [comment]
So it's not an issue with my key for sure ;)

**Comment by percula** [comment]
I had the same issue. Turns out I got an API key from the wrong google url:

Use this one: https://console.developers.google.com/apis
NOT this one: https://console.cloud.google.com/apis

No idea why they aren't the same...but hopefully this helps others that are banging their heads like I was.

**Comment by Moh09** [comment]
> Please try to open this URL:
> `https://maps.googleapis.com/maps/api/geocode/json?latlng=40.714224,-73.961452&key=[YOUR GEO KEY]`
> 
> I just need to be sure that the issue is library related and not a configuration or Google Maps issue.


What should I do if I have this as a result of the link?
   "error_message" : "This API project is not authorized to use this API.",
   "results" : [],
   "status" : "REQUEST_DENIED"

**Comment by rtchagas** [comment]
@Moh09 

You must enable Geocoding APIs in your project through this url:
https://console.cloud.google.com/google/maps-apis/api-list

**Comment by Moh09** [comment]
![Screenshot_2019-06-26-12-38-33](https://user-images.githubusercontent.com/46267191/60173937-31911080-9810-11e9-9222-190300b7a34c.png)
Thanks I have done it, it works now.
I still have the same display problem. (Maps, Geoloc, Places API are enabled. Maps works fine, Places and Geocoding have a rate of 100% error and Geoloc is never searched according to the dashboard of my console GCP). I have tried multiple keys changes to be sure that I didn't invert keys, I checked all keys according to the screen up here (8 may) whithout any changes.

**Comment by vanyasem** [comment]
In the meantime you can take a look at [Yandex Place Picker](https://github.com/vanyasem/YandexPlacePicker), which does basically the same for free utilising Yandex MapKit

**Comment by rtchagas** [comment]
Hi @Moh09 

Please double check your Android Key. It must be secured for Android Apps only and you must add the SHA1s from your app to it (including debug).

Regarding the Geolocation key, make sure that it is exactly this:
https://github.com/rtchagas/pingplacepicker/issues/10#issuecomment-490636289

Also test this link with your key:
https://maps.googleapis.com/maps/api/geocode/json?latlng=40.714224,-73.961452&key=YOUR_GEOCODING_KEY

If you still have problems, try to use an UNRESTRICTED key just for testing. This key should have no restrictions in both Applications and APIs. If PING works, the problem is with your keys. If it does not, we should investigate further.

**Comment by rtchagas** [comment]
> In the meantime you can take a look at [Yandex Place Picker](https://github.com/vanyasem/YandexPlacePicker), which does basically the same for free utilising Yandex MapKit

@vanyasem
Some credits for being based on PING would be nice :)

**Comment by vanyasem** [comment]
@rtchagas sure. PING is already linked in the description, but I will make it more clear that this library is partially based on PING (it only uses some of the UI components).

**Comment by NovakHonza** [comment]
Hi @rtchagas,
thank you for your great work.

I have similar problems as @dendyaziz with white icon color and white text color in buttons in place confirmation fragment. 

I understand that it is a problem with conflicting @color/colorPrimary in my app. I have "temporarily" solved these problems in this way:

- Button's text color with copy of `PingThemeBase` definition in my `styles.xml` and overwritten `colorPrimary` item. 
- To solve icon's color I had to make copy of  your`item_place.xml` to my `res/layout` directory and change tint color to requested value. 

With the solution for buttons I am quite OK but the solution for icons is not great because it forces me to check your `item_place.xml` after every upgrade for some potential incompatible changes.

Am I missing some better solution? 

And one last question on geocoding api key - if I understand it properly, it has to be absolutely unrestricted with enabled geocoding api?

**Comment by rtchagas** [comment]
Hi @NovakHonza 

Sorry, I missed your comment :(

Please check this issue for the icon and label colors: #30 

Regarding the Geolocation API key, it was moved to the Maps API key.
It must be [like this](https://raw.githubusercontent.com/rtchagas/pingplacepicker/master/images/maps_api_key.png)

**Comment by devpranav2104** [comment]
**Hi i have same issue **


java.lang.RuntimeException: Manifest merger failed with multiple errors, see logs
	at com.android.build.gradle.internal.tasks.manifest.ManifestHelperKt.mergeManifestsForApplication(ManifestHelper.kt:181)
	at com.android.build.gradle.tasks.ProcessApplicationManifest.doFullTaskAction(ProcessApplicationManifest.java:218)
	at com.android.build.gradle.tasks.ProcessApplicationManifest.doIncrementalTaskAction(ProcessApplicationManifest.java:324)
	at com.android.build.gradle.internal.tasks.IncrementalTask.handleIncrementalInputs(IncrementalTask.kt:111)
	at com.android.build.gradle.internal.tasks.IncrementalTask.access$handleIncrementalInputs(IncrementalTask.kt:64)
	at com.android.build.gradle.internal.tasks.IncrementalTask$taskAction$$inlined$recordTaskAction$1.invoke(AndroidVariantTask.kt:51)
	at com.android.build.gradle.internal.tasks.IncrementalTask$taskAction$$inlined$recordTaskAction$1.invoke(AndroidVariantTask.kt:31)
	at com.android.build.gradle.internal.tasks.Blocks.recordSpan(Blocks.java:91)
	at com.android.build.gradle.internal.tasks.IncrementalTask.taskAction$gradle(IncrementalTask.kt:134)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:103)
	at org.gradle.api.internal.project.taskfactory.IncrementalTaskInputsTaskAction.doExecute(IncrementalTaskInputsTaskAction.java:46)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:41)
	at org.gradle.api.internal.project.taskfactory.AbstractIncrementalTaskAction.execute(AbstractIncrementalTaskAction.java:25)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:28)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$5.run(ExecuteActionsTaskExecuter.java:404)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:393)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:376)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.access$200(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.execute(ExecuteActionsTaskExecuter.java:213)
	at org.gradle.internal.execution.steps.ExecuteStep.lambda$execute$0(ExecuteStep.java:32)
	at java.util.Optional.map(Optional.java:215)
	at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:32)
	at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:26)
	at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:58)
	at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:35)
	at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:48)
	at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:33)
	at org.gradle.internal.execution.steps.CancelExecutionStep.execute(CancelExecutionStep.java:39)
	at org.gradle.internal.execution.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:73)
	at org.gradle.internal.execution.steps.TimeoutStep.execute(TimeoutStep.java:54)
	at org.gradle.internal.execution.steps.CatchExceptionStep.execute(CatchExceptionStep.java:35)
	at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:51)
	at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:45)
	at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:31)
	at org.gradle.internal.execution.steps.CacheStep.executeWithoutCache(CacheStep.java:201)
	at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:70)
	at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:45)
	at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:49)
	at org.gradle.internal.execution.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:43)
	at org.gradle.internal.execution.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:32)
	at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:38)
	at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:24)
	at org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:96)
	at org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$0(SkipUpToDateStep.java:89)
	at java.util.Optional.map(Optional.java:215)
	at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:54)
	at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:38)
	at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:77)
	at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:37)
	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:36)
	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:26)
	at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:90)
	at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:48)
	at org.gradle.internal.execution.impl.DefaultWorkExecutor.execute(DefaultWorkExecutor.java:33)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:120)
	at org.gradle.api.internal.tasks.execution.ResolveBeforeExecutionStateTaskExecuter.execute(ResolveBeforeExecutionStateTaskExecuter.java:75)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:108)
	at org.gradle.api.internal.tasks.execution.ResolveBeforeExecutionOutputsTaskExecuter.execute(ResolveBeforeExecutionOutputsTaskExecuter.java:67)
	at org.gradle.api.internal.tasks.execution.ResolveAfterPreviousExecutionStateTaskExecuter.execute(ResolveAfterPreviousExecutionStateTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:94)
	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:95)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:73)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:49)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:49)
	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:43)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:355)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:343)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:336)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:322)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:134)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:129)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:202)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:193)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:129)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:748)

**Comment by eDR10x** [comment]
Hi GitHub Community, good day. How Enabling nearby searches?
where put this code?:
`<bool name="enable_nearby_search">true</bool>`

in the manifest.xml, activity.kt|java, or where? and this:

`<bool name="show_confirmation_photo">true</bool>`

  
`<bool name="show_confirmation_map">true</bool>`


`<bool name="auto_center_on_marker_click">false</bool>`

Because when I make click in the buttom, don't show the address name. Show some like that: _**3° 45' 37" S, 73° 15' 7" E**_. I need get the address name. Here i add the screenshot of real device.

Best Regards.
![Screenshot_20191211-174749_Ping Sample](https://user-images.githubusercontent.com/58796355/70676389-008b8780-1c5a-11ea-8579-9d27fbbb50eb.jpg)

**Comment by rtchagas** [comment]
Hi @eDR10x  

`<bool name="enable_nearby_search">true</bool>`

All those booleans are normal resources that you can add to your module res/values folder. 

I recommend to create a "config.xml" file and add them there. 

Regarding the place name, your Maps API key is wrong. That's why you got only the coordinates. 

Please take a look at https://github.com/rtchagas/pingplacepicker/blob/master/README.md#api-keys to know how to configure your Maps API key.

It must look like this https://raw.githubusercontent.com/rtchagas/pingplacepicker/master/images/maps_api_key.png

**Comment by eDR10x** [comment]
Hi @rtchagas thanks for your time and answer. I tryed it with your steps. But same. It show only coordinates. Here where i put the code `<bool>` and how i edited my API Key. Which could be the problem or the solution?
![config_enable_nearby_search](https://user-images.githubusercontent.com/58796355/70768127-ddcca200-1d31-11ea-9716-d97f1c6f6d9f.png)
![apis_choose](https://user-images.githubusercontent.com/58796355/70768368-cb9f3380-1d32-11ea-9181-fee62811a7aa.png)

**Comment by rtchagas** [comment]
Hi @eDR10x 

Your Maps API key looks good.

So, probably you have a bad Android API key.
Google's Places API uses the Android API key to fetch places info as well.

Please double check whether your Android API key is secured with your app's SHA1.
The SHA1 should be added for both debug and release versions.

For more info take a look at [here](https://developers.google.com/places/android-sdk/signup#restrict-key)

**Comment by eDR10x** [comment]
Hi @rtchagas good day. I had configured the "Android key" with sha-1 and package name. With the steps of the link. But is the same, show only coordinates. Here screenshot about the config. Or I must to activate the billing option in the console for this work, like that?  Thank for your support. Best regards.
![activate or not_billing](https://user-images.githubusercontent.com/58796355/70921485-5c576700-1ff2-11ea-8af1-53dca5d1f946.png)

![API_Key_status](https://user-images.githubusercontent.com/58796355/70921375-287c4180-1ff2-11ea-925d-357628c5f52f.png)
![Android API Key_good](https://user-images.githubusercontent.com/58796355/70921399-35009a00-1ff2-11ea-9d42-88ced1ba43fe.png)
![activate or not_billing](https://user-images.githubusercontent.com/58796355/70921861-164ed300-1ff3-11ea-90ee-78977c2239fd.png)

**Comment by GjoAbrahamN** [comment]
> `https://maps.googleapis.com/maps/api/geocode/json?latlng=40.714224,-73.961452&key=[YOUR GEO KEY]`

when try to use my Geolocation key i got the error "You must enable Billing on the Google Cloud Project at https://console.cloud.google.com/project/_/billing/enable Learn more at https://developers.google.com/maps/gmp-get-started" like this. what to do? do i need to enable this one?

**Comment by nourashouli** [comment]
nearby places is not loaded and API is true
how add this config to android kotlin project : <bool name="enable_nearby_search">true</bool>

**Comment by nourashouli** [comment]
nearby places is not loaded and API is true
how add this config to android kotlin project :
 "<boolean name=enable_nearby_search>true</boolean>"

**Comment by hemabhagnani** [comment]
@rtchagas  I have followed almost every step, still, my map is not able to load nearby places, and also when I search for a location nothing is happening. 
Please help !!!
