### ISSUE TITLE
Error after you turn off the location once and again turn on just before opening the pingplacepicker: java.lang.IllegalStateException: location must not be null

### ISSUE THREAD

**Issue by Katariaa** [rtchagas/pingplacepicker#2]
Process: com.android.example, PID: 32297
    java.lang.IllegalStateException: location must not be null
        at com.rtchagas.pingplacepicker.ui.PlacePickerActivity$getDeviceLocation$2.onSuccess(PlacePickerActivity.kt:236)
        at com.rtchagas.pingplacepicker.ui.PlacePickerActivity$getDeviceLocation$2.onSuccess(PlacePickerActivity.kt:47)
        at com.google.android.gms.tasks.zzn.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6863)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by rtchagas** [comment]
Thanks for the feedback!
I'm closing this issue with this commit.
https://github.com/rtchagas/pingplacepicker/commit/8bfaf0a9079ff234225c0256f5a81a208a5b30d6

A new release will be published.
