### ISSUE TITLE
Improvement: Update koin version

### ISSUE THREAD

**Issue by lemberh** [rtchagas/pingplacepicker#24]
I'm using latest stable version of koin in my project:
```
def koin_version = '2.0.1'
implementation "org.koin:koin-android:$koin_version"
```
In pingplacepicker this version is used:
`implementation 'org.koin:koin-android:2.0.0-rc-2'`
When I'm starting PlacePicker it crashes. Stacktrace point to Koin dependencies in library. 
```
 java.lang.NoSuchMethodError: No direct method <init>(Lorg/koin/core/qualifier/Qualifier;Lkotlin/reflect/KClass;)V in class Lorg/koin/core/definition/BeanDefinition; or its super classes (declaration of 'org.koin.core.definition.BeanDefinition' appears in /data/app/com.oitchau.debug-RnTBdgwQJYqnF5iT34jFRQ==/split_lib_slice_0_apk.apk!classes3.dex)
        at com.rtchagas.pingplacepicker.inject.RepositoryModuleKt$repositoryModule$1.invoke(RepositoryModule.kt:57)
        at com.rtchagas.pingplacepicker.inject.RepositoryModuleKt$repositoryModule$1.invoke(Unknown Source:2)
        at org.koin.dsl.ModuleKt.module(Module.kt:31)
        at org.koin.dsl.ModuleKt.module$default(Module.kt:29)
        at com.rtchagas.pingplacepicker.inject.RepositoryModuleKt.<clinit>(RepositoryModule.kt:17)
        at com.rtchagas.pingplacepicker.inject.RepositoryModuleKt.getRepositoryModule(RepositoryModule.kt:17)
        at com.rtchagas.pingplacepicker.PingPlacePicker$IntentBuilder$initKoin$1.invoke(PingPlacePicker.kt:74)
        at com.rtchagas.pingplacepicker.PingPlacePicker$IntentBuilder$initKoin$1.invoke(PingPlacePicker.kt:20)
        at org.koin.dsl.KoinApplicationKt.koinApplication(KoinApplication.kt:28)
        at com.rtchagas.pingplacepicker.PingPlacePicker$IntentBuilder.initKoin(PingPlacePicker.kt:70)
        at com.rtchagas.pingplacepicker.PingPlacePicker$IntentBuilder.build(PingPlacePicker.kt:52)
```
Due to gradle default dependency resolving strategy it pick higher version of the library, so when I decreased dependency in my project to `2.0.0-rc2` the PingPlacePicker starded working.
So could you please update this dependency in the next release

**Comment by rtchagas** [comment]
Hi @lemberh 

Thanks for pointing this out! I'll update it for the next release.

Thank you!

**Comment by lemberh** [comment]
No, thank you for this widget, it saved me a lot of time. :)
One more remark, you are using in library this dependency `implementation 'com.squareup.okhttp3:logging-interceptor:3.14.1'` which depend on **okhhp-3.14** and this version minimum supported android is 21+ as you can see in changelog https://github.com/square/okhttp/blob/master/CHANGELOG.md#version-3130
I suggest to stick to version `3.12.3` which still supports older versions.

**Comment by rtchagas** [comment]
https://github.com/rtchagas/pingplacepicker/commit/c617506b434a3ef380c4fc1e90f9abdd7a7bc9cf

I'm validating the new version, and all those changes will be published soon.

**Comment by rtchagas** [comment]
https://github.com/rtchagas/pingplacepicker/releases/tag/1.1.0
