### ISSUE TITLE
Cann't inflating class androidx.coordinatorlayout.widget.CoordinatorLayout

### ISSUE THREAD

**Issue by DuMintong** [rtchagas/pingplacepicker#27]
Add the library to my project and run to crash.   
It seems that error is "class androidx.coordinatorlayout.widget.CoordinatorLayout".

  java.lang.RuntimeException: Unable to start activity ComponentInfo{cn.oneplus.opmms/com.rtchagas.pingplacepicker.ui.PlacePickerActivity}: android.view.InflateException: Binary XML file line #2 in cn.oneplus.opmms:layout/activity_place_picker: Binary XML file line #2 in cn.oneplus.opmms:layout/activity_place_picker: Error inflating class androidx.coordinatorlayout.widget.CoordinatorLayout
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3368)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3507)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2106)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7512)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:530)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:948)
     Caused by: android.view.InflateException: Binary XML file line #2 in cn.oneplus.opmms:layout/activity_place_picker: Binary XML file line #2 in cn.oneplus.opmms:layout/activity_place_picker: Error inflating class androidx.coordinatorlayout.widget.CoordinatorLayout
     Caused by: android.view.InflateException: Binary XML file line #2 in cn.oneplus.opmms:layout/activity_place_picker: Error inflating class androidx.coordinatorlayout.widget.CoordinatorLayout
     Caused by: java.lang.ClassNotFoundException: androidx.coordinatorlayout.widget.CoordinatorLayout

**Comment by rtchagas** [comment]
Hi @DuMintong 

Have you enabled AndroidX in your project?

If so, please check if you've added this dependency:
https://github.com/rtchagas/pingplacepicker/blob/f24e5fd5ed981d02ea67c3a08c8cdacd3f8a5e4e/sample/build.gradle#L44

**Comment by DuMintong** [comment]
Hi rectagas,

I has enabled AndroidX in my project, and i can used CoordinatorLayout normally in my code.
Like: import androidx.coordinatorlayout.widget.CoordinatorLayout;
This is dependencies part of my build.gradle file:
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    testImplementation 'junit:junit:4.12'
/*    implementation ('com.android.support:appcompat-v7:28.0.0')*/
    implementation 'androidx.appcompat:appcompat:1.1.0-rc01'
    implementation 'com.google.android.gms:play-services-location:10.2.0'
    implementation 'com.google.android.libraries.places:places:1.1.0'
    // PING Place Picker
    implementation 'com.github.rtchagas:pingplacepicker:1.0.+'
}

**Comment by DuMintong** [comment]
I have found the reason, because i add below code section in project build.gradle file. And delete then OK.

   /* subprojects {
        project.configurations.all {
            resolutionStrategy.eachDependency { details ->
                if (details.requested.group == 'com.android.support'
                        && !details.requested.name.contains('multidex') ) {
                    details.useVersion "27.1.1"
                }

                if (details.requested.group == 'androidx.core'
                        && !details.requested.name.contains('androidx') ) {
                    details.useVersion "1.0.1"
                }
            }
        }
    }*/

**Comment by DuMintong** [comment]
resloved
