### ISSUE TITLE
Crash on calling activity, rvNearbyPlaces missing.

### ISSUE THREAD

**Issue by Trust-Coder** [rtchagas/pingplacepicker#32]
`Process: gps_route_finder_nearby_video.navigation.direction, PID: 19561
    java.lang.NoSuchFieldError: No static field rvNearbyPlaces of type I in class Lcom/rtchagas/pingplacepicker/R$id; or its superclasses (declaration of 'com.rtchagas.pingplacepicker.R$id' appears in /data/app/gps_route_finder_nearby_video.navigation.direction-SNqdVdncdDTkgxdQO8CE5Q==/split_lib_slice_0_apk.apk)
        at com.rtchagas.pingplacepicker.ui.PlacePickerActivity.initializeUi(PlacePickerActivity.kt:367)
        at com.rtchagas.pingplacepicker.ui.PlacePickerActivity.onCreate(PlacePickerActivity.kt:119)
        at android.app.Activity.performCreate(Activity.java:7327)
        at android.app.Activity.performCreate(Activity.java:7318)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1275)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3095)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3258)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1955)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7073)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
`

**Comment by rtchagas** [comment]
Hi @Trust-Coder 

This is something related to your project as PING's main activity does have the rvNearbyPlaces recycler view.
https://github.com/rtchagas/pingplacepicker/blob/5c16d2df710d12c0f903d5a5f691f2d9e84e4c0d/library/src/main/res/layout/activity_place_picker.xml#L191

Did you manage to solve it? Please be sure that you didn't override the layout file for PING activity.
