### ISSUE TITLE
PlacePickerActivity crash when reopen the activity without location permission

### ISSUE THREAD

**Issue by DuMintong** [rtchagas/pingplacepicker#34]
Disable app's location permisson and reopen the PlacePickerActivity from recent app menu , then it carsh.   100% Probability.

2019-07-22 10:25:09.642 24929-24929/cn.oneplus.opmms D/AndroidRuntime: Shutting down VM
2019-07-22 10:25:09.642 24929-24929/cn.oneplus.opmms E/AndroidRuntime: FATAL EXCEPTION: main
    Process: cn.oneplus.opmms, PID: 24929
    kotlin.KotlinNullPointerException
        at com.rtchagas.pingplacepicker.inject.PingKoinComponent$DefaultImpls.getKoin(PingKoinComponent.kt:15)
        at com.rtchagas.pingplacepicker.ui.PlacePickerActivity.getKoin(PlacePickerActivity.kt:53)
        at org.koin.android.ext.android.ComponentCallbackExtKt.getKoin(ComponentCallbackExt.kt:14)
        at org.koin.android.viewmodel.ext.android.LifecycleOwnerExtKt.getKoin(LifecycleOwnerExt.kt:71)
        at org.koin.android.viewmodel.ext.android.LifecycleOwnerExtKt.getViewModel(LifecycleOwnerExt.kt:85)
        at com.rtchagas.pingplacepicker.ui.PlacePickerActivity$$special$$inlined$viewModel$1.invoke(LifecycleOwnerExt.kt:95)
        at com.rtchagas.pingplacepicker.ui.PlacePickerActivity$$special$$inlined$viewModel$1.invoke(Unknown Source:0)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at com.rtchagas.pingplacepicker.ui.PlacePickerActivity.getViewModel(Unknown Source:7)
        at com.rtchagas.pingplacepicker.ui.PlacePickerActivity.refreshNearbyPlaces(PlacePickerActivity.kt:490)
        at com.rtchagas.pingplacepicker.ui.PlacePickerActivity.access$refreshNearbyPlaces(PlacePickerActivity.kt:53)
        at com.rtchagas.pingplacepicker.ui.PlacePickerActivity$handler$1.handleMessage(PlacePickerActivity.kt:204)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6940)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by DuMintong** [comment]
New logs:

    java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=42, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {cn.oneplus.opmms/com.karumi.dexter.DexterActivity}: kotlin.KotlinNullPointerException
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4956)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4997)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2106)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7512)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:530)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:948)
     Caused by: kotlin.KotlinNullPointerException
        at com.rtchagas.pingplacepicker.inject.PingKoinComponent$DefaultImpls.getKoin(PingKoinComponent.kt:15)
        at com.rtchagas.pingplacepicker.ui.PlacePickerActivity.getKoin(PlacePickerActivity.kt:51)
        at org.koin.android.viewmodel.ext.android.LifecycleOwnerExtKt.getKoin(LifecycleOwnerExt.kt:75)
        at com.rtchagas.pingplacepicker.ui.PlacePickerActivity$$special$$inlined$viewModel$1.invoke(LifecycleOwnerExt.kt:107)
        at com.rtchagas.pingplacepicker.ui.PlacePickerActivity$$special$$inlined$viewModel$1.invoke(Unknown Source:0)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at com.rtchagas.pingplacepicker.ui.PlacePickerActivity.getViewModel(Unknown Source:7)
        at com.rtchagas.pingplacepicker.ui.PlacePickerActivity.loadNearbyPlaces(PlacePickerActivity.kt:422)
        at com.rtchagas.pingplacepicker.ui.PlacePickerActivity.initMap(PlacePickerActivity.kt:413)
        at com.rtchagas.pingplacepicker.ui.PlacePickerActivity.access$initMap(PlacePickerActivity.kt:51)
        at com.rtchagas.pingplacepicker.ui.PlacePickerActivity$checkForPermission$1.onPermissionGranted(PlacePickerActivity.kt:217)
        at com.karumi.dexter.listener.single.CompositePermissionListener.onPermissionGranted(Unknown Source:18)
        at com.karumi.dexter.MultiplePermissionsListenerToPermissionListenerAdapter.onPermissionsChecked(Unknown Source:35)
        at com.karumi.dexter.MultiplePermissionListenerThreadDecorator$1.run(Unknown Source:8)
        at com.karumi.dexter.MainThread.execute(Unknown Source:6)
        at com.karumi.dexter.MultiplePermissionListenerThreadDecorator.onPermissionsChecked(Unknown Source:7)
        at com.karumi.dexter.DexterInstance.onPermissionsChecked(Unknown Source:57)
        at com.karumi.dexter.DexterInstance.updatePermissionsAsGranted(Unknown Source:26)
        at com.karumi.dexter.DexterInstance.onPermissionRequestGranted(Unknown Source:0)
        at com.karumi.dexter.Dexter.onPermissionsRequested(Unknown Source:4)
        at com.karumi.dexter.DexterActivity.onRequestPermissionsResult(Unknown Source:51)
        at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:8289)
        at android.app.Activity.dispatchActivityResult(Activity.java:8139)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4949)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4997) 
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2106) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7512) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:530) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:948)
