### ISSUE TITLE
Androidx fragment crash

### ISSUE THREAD

**Issue by t104360088** [rtchagas/pingplacepicker#35]
Hi @rtchagas
When I use this library in a java project, I got the strange errors
1. My project layout have wrong position in ConstraintLayout
2. I got the crash in androidx fragment

This is crash message:
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean androidx.fragment.app.FragmentManagerImpl.isDestroyed()' on a null object reference
        at androidx.fragment.app.Fragment.performDetach(Fragment.java:2844)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1034)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:434)
        at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2076)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1866)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1821)
        at androidx.fragment.app.FragmentManagerImpl.execSingleAction(FragmentManagerImpl.java:1696)
        at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:299)
        at androidx.fragment.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:256)
        at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1244)
        at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1092)
        at androidx.viewpager.widget.ViewPager$3.run(ViewPager.java:273)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:966)
        at android.view.Choreographer.doCallbacks(Choreographer.java:778)
        at android.view.Choreographer.doFrame(Choreographer.java:710)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:169)
        at android.app.ActivityThread.main(ActivityThread.java:6585)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

Do you have any idea? Thanks for you help

**Comment by rtchagas** [comment]
Hi @t104360088 

Probably your project's dependencies are conflicting with PING's.
Check this issue #33 

But the Fragment issue is really unexpected.... PING does not change any default fragment behaviour. I would suggest you to remove PING and try to update your androidx dependencies. Check if your project still crashes.

**Comment by t104360088** [comment]
Thanks for your reply
1. ConstraintLayout library conflict
2. I have the older code in project, and androidx.appcompat:appcompat:1.1.0-rc01 is already removed

This is solution about 2:
https://stackoverflow.com/questions/56618453/after-migrating-to-androidx-application-crashes-with-attempt-to-invoke-androidx

**Comment by MadhuriQuickride** [comment]
check 
 @Override
    protected void onDestroy() {
  super.onDestroy();
.....
}

check   super.onDestroy();  should be top on this method.
your all content should be below to   super.onDestroy();
