### ISSUE TITLE
Crash happens when "Places must be initialized."

### ISSUE THREAD

**Issue by DuMintong** [rtchagas/pingplacepicker#37]
Hi  rtchagas,

   A crash occurs when clicking the search box in the PlacePickerActivity. And the probability 100% that time. Maybe there is something wrong with the network at that time.  I close and open this activity and it becomes normal.

2019-07-30 15:05:18.680 24771-24771/cn.oneplus.opmms D/AndroidRuntime: Shutting down VM
2019-07-30 15:05:18.682 24771-24771/cn.oneplus.opmms E/AndroidRuntime: FATAL EXCEPTION: main
    Process: cn.oneplus.opmms, PID: 24771
    java.lang.RuntimeException: Unable to start activity ComponentInfo{cn.oneplus.opmms/com.google.android.libraries.places.widget.AutocompleteActivity}: java.lang.IllegalStateException: Places must be initialized.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3047)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3182)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1916)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6898)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.IllegalStateException: Places must be initialized.
        at com.google.android.libraries.places.internal.go.b(PG:22)
        at com.google.android.libraries.places.widget.AutocompleteActivity.onCreate(PG:2)
        at android.app.Activity.performCreate(Activity.java:7149)
        at android.app.Activity.performCreate(Activity.java:7140)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1288)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3027)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3182) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1916) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6898) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by omaisali** [comment]
Same issue, Any solution please ?

**Comment by pascaleandrei** [comment]
Same here. If I do not have location on, it crashes when clicking the search box.

**Comment by Dararii** [comment]
why this case closed? is there any solution available?

**Comment by rtchagas** [comment]
Yes, it was fixed by this commit https://github.com/rtchagas/pingplacepicker/commit/5d0c971ce3f35c130ef765de1394e5811e4c5174 and released in version 1.1.4
