### ISSUE TITLE
 The style on this component requires your app theme to be Theme.MaterialComponents

### ISSUE THREAD

**Issue by sharukhmohammed** [rtchagas/pingplacepicker#39]
Hello,

in `onCreateActivity` in at `setContentView`
I encounter this error for TextInputLayout inflation. Its style is already set to                         `style="@style/Widget.MaterialComponents.TextInputLayout.FilledBox"`

But I get a crash when I just include your library. (Not even used in the activity) 

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{rentsher.simba.uae/rentsher.simba.modules.setAddress.SetAddressActivity}: android.view.InflateException: Binary XML file line #58: Binary XML file line #58: Error inflating class com.google.android.material.textfield.TextInputLayout
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2951)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: android.view.InflateException: Binary XML file line #58: Binary XML file line #58: Error inflating class com.google.android.material.textfield.TextInputLayout
     Caused by: android.view.InflateException: Binary XML file line #58: Error inflating class com.google.android.material.textfield.TextInputLayout
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:647)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:545)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:161)
        at rentsher.simba.modules.setAddress.SetAddressActivity.onCreate(SetAddressActivity.kt:43)
        at android.app.Activity.performCreate(Activity.java:7144)
        at android.app.Activity.performCreate(Activity.java:7135)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2931)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
2019-08-07 14:57:39.434 31922-31922/rentsher.simba.uae E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.IllegalArgumentException: The style on this component requires your app theme to be Theme.MaterialComponents (or a descendant).
        at com.google.android.material.internal.ThemeEnforcement.checkTheme(ThemeEnforcement.java:240)
        at com.google.android.material.internal.ThemeEnforcement.checkMaterialTheme(ThemeEnforcement.java:215)
        at com.google.android.material.internal.ThemeEnforcement.checkCompatibleTheme(ThemeEnforcement.java:143)
        at com.google.android.material.internal.ThemeEnforcement.obtainTintedStyledAttributes(ThemeEnforcement.java:116)
        at com.google.android.material.textfield.TextInputLayout.<init>(TextInputLayout.java:413)
        at com.google.android.material.textfield.TextInputLayout.<init>(TextInputLayout.java:392)
```

When I remove your library from `build.gradle`  everything works as usual

here is my current build.gradle (commenting last two lines doenst lead to crash)
```

 implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'androidx.appcompat:appcompat:1.0.2'

    //Basic
    implementation 'com.google.android.material:material:1.0.0'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    implementation 'androidx.recyclerview:recyclerview:1.0.0'
    implementation 'androidx.cardview:cardview:1.0.0'

    //Play Services
    implementation 'com.google.android.gms:play-services-location:17.0.0'
    implementation 'com.google.android.gms:play-services-maps:17.0.0'
    implementation 'com.google.android.gms:play-services-auth:17.0.0'

    //Kotlin Coroutines
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.1.1'

    //Firebase
    implementation 'com.google.firebase:firebase-core:17.0.1'
    implementation 'com.google.firebase:firebase-messaging:19.0.1'
    implementation 'com.google.firebase:firebase-auth:18.1.0'

    //Facebook
    implementation 'com.facebook.android:facebook-login:4.42.0'

    //Netcore Smartech
    implementation 'in.netcore.smartechfcm:smartech-fcm:1.2.7'
    implementation 'com.firebase:firebase-jobdispatcher:0.8.5'

    //Firebase Auth
    //implementation 'com.google.firebase:firebase-auth:16.1.0'
    //implementation 'com.firebaseui:firebase-ui-auth:4.1.0'

    //Firebase Firestore
    //implementation 'com.google.firebase:firebase-database:16.0.6'
    //implementation 'com.firebaseui:firebase-ui-database:4.3.1'

    //Firebase Storage
    //implementation 'com.google.firebase:firebase-storage:16.0.5'
    //implementation 'com.firebaseui:firebase-ui-storage:4.3.1'

    //Reactive
    implementation 'io.reactivex.rxjava2:rxandroid:2.1.1'
    implementation 'io.reactivex.rxjava2:rxjava:2.2.10'

    // Networking
    implementation 'com.squareup.retrofit2:retrofit:2.6.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.5.0'
    implementation 'com.squareup.okhttp3:logging-interceptor:3.13.1'
    implementation 'com.squareup.retrofit2:adapter-rxjava2:2.6.0'
    implementation 'com.jakewharton.retrofit:retrofit2-kotlin-coroutines-adapter:0.9.2'
    debugImplementation 'com.readystatesoftware.chuck:library:1.1.0'

    //RecyclerView Decoration
    implementation 'com.arjinmc.android:recyclerviewdecoration:2.6'

    // Gson by Google
    implementation 'com.google.code.gson:gson:2.8.5'

    //Glide
    implementation 'com.github.bumptech.glide:glide:4.9.0'
    kapt 'com.github.bumptech.glide:compiler:4.9.0'

    //Location Library
    implementation 'io.nlopez.smartlocation:library:3.3.3'

    //Permissions
    implementation 'com.karumi:dexter:5.0.0'

    //Crashlytics
    implementation 'com.crashlytics.sdk.android:crashlytics:2.10.1'

    //AppCountry Code Picker
    implementation 'com.hbb20:ccp:2.1.2'

    //File Chooser
    implementation 'com.github.hedzr:android-file-chooser:v1.1.16'

    //Camera Take Pic
    implementation 'com.sandrios.android:sandriosCamera:1.1.0'
    implementation 'com.github.yalantis:ucrop:2.2.2'
    implementation 'id.zelory:compressor:2.1.0'

    //Calendar
    implementation 'com.savvi.datepicker:rangepicker:1.3.0'
    
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.2.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'

    // Places library
    implementation 'com.google.android.libraries.places:places:2.0.0'
    // PING Place Picker
    implementation 'com.github.rtchagas:pingplacepicker:1.1.2'

```

**Comment by rtchagas** [comment]
Hi @sharukhmohammed 

PING doesn't requires your app to inherit from MaterialTheme.
You can check the demo project to see that it uses the AppCompat theme.

You got this issue because, as you said, you're setting the material theme to all TextInputLayouts.

When you added PING, you've bumped your MaterialComponents library to **1.1.0-alpha9** version.
This version is enforcing the app theme to be MaterialTheme as the TextIputLayout style was set.

You can workaround this by retaining your previous MaterialComponents library version:
```
android {
    configurations.all {
        resolutionStrategy.force 'com.google.android.material:material:1.0.0'
    }
}
```
But I believe that sooner or later you'll need to update your Material Library. So, it would be good to start migrating your app theme to Material.

**Comment by rtchagas** [comment]
I'm closing this issue.
If you still have any doubt, please reopen it.
