### ISSUE TITLE
 java.lang.NoSuchFieldError: No static field rvNearbyPlaces of type I in class Lcom/rtchagas/pingplacepicker/R$id; or its superclasses (declaration of 'com.rtchagas.pingplacepicker.R$id' appears  

### ISSUE THREAD

**Issue by wdnk** [rtchagas/pingplacepicker#58]
```
02-19 19:29:21.903 21021-21021/ptsinergiterangbangsa.listrikon.pelanggan E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ptsinergiterangbangsa.listrikon.pelanggan, PID: 21021
    java.lang.NoSuchFieldError: No static field rvNearbyPlaces of type I in class Lcom/rtchagas/pingplacepicker/R$id; or its superclasses (declaration of 'com.rtchagas.pingplacepicker.R$id' appears in /data/app/ptsinergiterangbangsa.listrikon.pelanggan-2/base.apk:classes2.dex)
        at com.rtchagas.pingplacepicker.ui.PlacePickerActivity.initializeUi(PlacePickerActivity.kt:367)
        at com.rtchagas.pingplacepicker.ui.PlacePickerActivity.onCreate(PlacePickerActivity.kt:119)
        at android.app.Activity.performCreate(Activity.java:6355)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2440)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2547)
        at android.app.ActivityThread.access$1100(ActivityThread.java:151)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1398)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:157)
        at android.app.ActivityThread.main(ActivityThread.java:5603)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:774)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:652)
```

I don't have any idea what the cause of this issue. Any help?

**Comment by rtchagas** [comment]
Hi @wdnk 
This error is related to your project configuration.
Please make sure you add the kotlin plugins at the top of your project's build.gradle

```gradle
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
```

**Comment by wdnk** [comment]
i already added:

> apply plugin: 'kotlin-android'
> apply plugin: 'kotlin-android-extensions'

But the problem still occur.

**Comment by rtchagas** [comment]
Did you try to run the sample app?
