### ISSUE TITLE
 java.lang.UnsupportedOperationException  crash when open picker

### ISSUE THREAD

**Issue by Rahul-Openxcell** [rtchagas/pingplacepicker#6]
` java.lang.UnsupportedOperationException
        at com.google.android.libraries.places.internal.hv.set(PG:3)
        at java.util.List.sort(List.java:504)
        at java.util.Collections.sort(Collections.java:201)
        at kotlin.collections.CollectionsKt__MutableCollectionsJVMKt.sortWith(MutableCollectionsJVM.kt:38)
        at com.rtchagas.pingplacepicker.repository.googlemaps.GoogleMapsRepository.sortByLikelihood(GoogleMapsRepository.kt:146)
        at com.rtchagas.pingplacepicker.repository.googlemaps.GoogleMapsRepository.access$sortByLikelihood(GoogleMapsRepository.kt:21)
        at com.rtchagas.pingplacepicker.repository.googlemaps.GoogleMapsRepository$getNearbyPlaces$1$1.onComplete(GoogleMapsRepository.kt:46)
        at com.google.android.gms.tasks.zzj.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6518)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)`

**Comment by Rahul-Openxcell** [comment]
I have use this place libarry:
com.google.android.libraries.places:places:1.1.0

**Comment by rtchagas** [comment]
@Rahul-Openxcell 

Did you try to run the sample project? Is it crashing as well?

I'm asking that because I've tested the picker in many devices and Android versions and didn't get this crash.

Could you please also tell which Android version and target API are you building the app to?

**Comment by Rahul-Openxcell** [comment]
@rtchagas 
When I am use com.google.android.libraries.places:places:1.0.0 is working fine but update library is not working  com.google.android.libraries.places:places:1.1.0

**Comment by Rahul-Openxcell** [comment]
@rtchagas 
Please add this dependencies your sample project (update version 1.1.0) 
com.google.android.libraries.places:places:**1.1.0**
