### ISSUE TITLE
After sometime, unfortunately Apps crashed.

### ISSUE THREAD

**Issue by AhmadullahSaikat** [rtchagas/pingplacepicker#64]
2020-03-05 14:14:57.323 22403-22403/com.muslim.quran_bangla E/CustomActivityOnCrash: The previous app process crashed. This is the stack trace of the crash:
    android.database.sqlite.SQLiteReadOnlyDatabaseException: attempt to write a readonly database (code 1032 SQLITE_READONLY_DBMOVED[1032])
        at android.database.sqlite.SQLiteConnection.nativeExecute(Native Method)
        at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:759)
        at android.database.sqlite.SQLiteSession.execute(SQLiteSession.java:619)
        at android.database.sqlite.SQLiteStatement.execute(SQLiteStatement.java:44)
        at com.google.android.datatransport.runtime.scheduling.persistence.SQLiteEventStore.lambda$recordFailure$3(com.google.android.datatransport:transport-runtime@@2.1.0:189)
        at com.google.android.datatransport.runtime.scheduling.persistence.SQLiteEventStore$$Lambda$7.apply(Unknown Source:4)
        at com.google.android.datatransport.runtime.scheduling.persistence.SQLiteEventStore.inTransaction(com.google.android.datatransport:transport-runtime@@2.1.0:483)
        at com.google.android.datatransport.runtime.scheduling.persistence.SQLiteEventStore.recordFailure(com.google.android.datatransport:transport-runtime@@2.1.0:187)
        at com.google.android.datatransport.runtime.scheduling.jobscheduling.Uploader.lambda$logAndUpdateState$3(com.google.android.datatransport:transport-runtime@@2.1.0:131)
        at com.google.android.datatransport.runtime.scheduling.jobscheduling.Uploader$$Lambda$3.execute(Unknown Source:10)
        at com.google.android.datatransport.runtime.scheduling.persistence.SQLiteEventStore.runCriticalSection(com.google.android.datatransport:transport-runtime@@2.1.0:471)
        at com.google.android.datatransport.runtime.scheduling.jobscheduling.Uploader.logAndUpdateState(com.google.android.datatransport:transport-runtime@@2.1.0:128)
        at com.google.android.datatransport.runtime.scheduling.jobscheduling.Uploader.lambda$upload$1(com.google.android.datatransport:transport-runtime@@2.1.0:88)
        at com.google.android.datatransport.runtime.scheduling.jobscheduling.Uploader$$Lambda$1.run(Unknown Source:8)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)

**Comment by rtchagas** [comment]
Hi @AhmadullahSaikat 

PING doesn't use any SQLITE database by itself.

This probably is a problem with some running Google Service.
