### ISSUE TITLE
pingplacepicker is crushing 

### ISSUE THREAD

**Issue by yusuf-murodov** [rtchagas/pingplacepicker#84]
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: me.modernpage.googlemapsgoogleplaces, PID: 13163
    java.lang.NoClassDefFoundError: Failed resolution of: Lkotlin/jvm/internal/Intrinsics;
        at com.rtchagas.pingplacepicker.PingPlacePicker$IntentBuilder.setAndroidApiKey(Unknown Source:2)
        at me.modernpage.googlemapsgoogleplaces.MapActivity$6.onClick(MapActivity.java:218)
        at android.view.View.performClick(View.java:6256)
        at android.view.View$PerformClick.run(View.java:24701)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "kotlin.jvm.internal.Intrinsics" on path: DexPathList[[zip file "/data/app/me.modernpage.googlemapsgoogleplaces-2G6k78GebY3L06kT-PcBBw==/base.apk"],nativeLibraryDirectories=[/data/app/me.modernpage.googlemapsgoogleplaces-2G6k78GebY3L06kT-PcBBw==/lib/x86, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)

I already added the kotlin dependency
implementation 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.3.61'

**Comment by rtchagas** [comment]
Hello!
This is related to Kotlin version. If your app is targeting 1.4 or later it gonna crash.
This was fixed in the release 2.2.0.
